# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MeetGeek' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeetGeek
    pod 'Firebase/Core'
    pod 'Firebase/Database'
end
